// src/types/index.ts
// Re-export all types for convenient imports

export type * from "./invitation";

// Database types (will be generated by Supabase CLI later)
// For now, define manually based on DATABASE.md schema

export interface RSVPRow {
  id: string;
  invitation_slug: string;
  guest_name: string;
  attendance: "hadir" | "tidak_hadir";
  pax_count: number;
  notes: string | null;
  created_at: string;
}

export interface RSVPInsert {
  invitation_slug: string;
  guest_name: string;
  attendance: "hadir" | "tidak_hadir";
  pax_count?: number;
  notes?: string | null;
}

export interface WishRow {
  id: string;
  invitation_slug: string;
  guest_name: string;
  message: string;
  is_visible: boolean;
  created_at: string;
}

export interface WishInsert {
  invitation_slug: string;
  guest_name: string;
  message: string;
}

// Template type
export interface Template {
  id: string;
  slug: string;
  name: string;
  description: string;
  tags: string[];
  demoSlug: string;
  thumbnailUrl: string;
  ogImageUrl?: string;
  features: string[];
  style: "modern" | "minimalist" | "floral" | "traditional";
}

// Server Action response shape
export type ActionResult<T = void> =
  | { success: true; data?: T }
  | { success: false; error: string | Record<string, string[]> };
